### ISSUE TITLE
重写onClick(v: View)方法、并在内部调用XXX.onClick(v)会有问题

### ISSUE THREAD

**Issue by aaaaaaaazmx** [leavesCZY/Track#1]
public AAA setLeftClickListener(OnClickListener onClickListener) {
        this.leftClickListener = onClickListener;
        return this;
    }

@Override
    public void onClick(View v) {
        if (v.getId() == R.id.iv_back || v.getId() == R.id.tv_left_name) {
           leftClickListener.onClick(v);
         }
    }
没办法，陈年老代码。。。
原因是因为 leftClickListener.onClick(v);又回调到了重写的onClick方法中，此时间隔时间还没满足。

**Comment by leavesCZY** [comment]
@aaaaaaaazmx 这个感觉我没办法解决啊，，这种嵌套调用的关系 Trace 也识别不出来。。。。

**Comment by leavesCZY** [comment]
补充一下。示例代码中的 ViewClickMonitor 是全局所有 View 对象共享同一个时间戳，相当于不同 View 之间的点击事件是会相互影响的。而如果你这里再次回调时是不同的 View 的话，那么可以将 ViewClickMonitor 改为不同的 View 独享一个时间戳，这样就可以解决你这个问题了

**Comment by aaaaaaaazmx** [comment]
> 
是这么回事，懒得添加判断了，反正实际执行的是下面的onClick(v),在上方添加一个unCheck注解也能解决。
