### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by Bert-King** [leavesCZY/Track#3]
Plugin [id: 'io.github.leavesczy.trace'] was not found in any of the following sources.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.github.leavesczy.trace'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)

**Comment by leavesCZY** [comment]
你是如何声明 plugin 的呢？repositories 确定有包含 gradlePluginPortal() 吗
