### ISSUE TITLE
自定义拦截aop

### ISSUE THREAD

**Issue by HeYongRui** [leavesCZY/Track#4]
我有以下三个问题，可以解答吗？谢谢
1、请问添加自定义methodname拦截，是在config中的setof中新增吗，我用的另外的baseadapter
2、怎么可以打印出点击的methodname日志呢
3、我想自己把trace模块源码弄到本地，并且加载到我的项目里用，怎么配置classpath和apply plugin呢

**Comment by leavesCZY** [comment]
1、我不明白你说的 “自定义methodname拦截” 是指什么
2、你是指打印出每次的点击事件？那在你自定义的 ViewClickMonitor 里打印就好呀
3、这个你可以参考我另一个项目，用 buildSrc 来实现：https://github.com/leavesCZY/asm-samples

**Comment by HeYongRui** [comment]
1、自定义拦截，就是我有第三方的recycleview的adapter点击事件，它的包名和baseadapter不同，测试防抖无效，可能需要在hooklist内加入这个路径？
2、因为我不清楚实际运行时第三方的recycleview的adapter点击函数路径，所以想通过看日志拿到需要hook的路径再添加到hooklist中，这个在viewClickmonitor中应该看不到的，应该是要在factory中的hook函数中打印才能看到吧，现在调试看不到
3、我项目用的旧的gradle配置形式，没有DSL这些新的特性，有没有旧版本的配置方式参考啊，我迁移新版本gradle成本太大了

其实有个建议，看看可否考虑呢，就是可以把hookpointlist暴露一个add的入口给接入方在gradle中配置，用户可自行配置新增拦截路径；还有可否实现一个注解里面加入时间参数，达到单独控制某一个Click的拦截间隔时间

**Comment by leavesCZY** [comment]
1、2：include 和 exclude 均没有传值的情况下，viewClickTrace 是会对整个项目中的所有 OnClickListener 均生效的。你会不生效是因为你有向这两个参数传值且排除了第三方的 RecycleView 的点击事件？？另外，你无需知道 RecycleView 的点击事件具体是在哪里，你只要知道它的包名前缀就够了。 wiki 里都有详细介绍
3、想直接集成源码到你项目中的话就需要你自己研究了，我都是用的 kts

最后，感觉你是不是搞混了 Trace 和 asm-samples 这两个项目？？hookPointList 这个词听起来是我在 asm-samples 这个库里的代码。asm-samples 属于我的个人 demo，本来就是只能开发者自己引入源码到自己项目中。Trace 则有被我发布到 mavenCentral，是支持直接远程依赖，且用 grovy 方式来引入的

**Comment by HeYongRui** [comment]
1、2：没有设置include之类的，测试就是没有生效，我看好像是通过recycleview的addonitemtouchlistener设置的点击事件，是不是因为这样才没生效，有没有什么办法可以使这个也生效呢
3：那trace和samples两个项目的功能模块是一样的吗

**Comment by leavesCZY** [comment]
我不太了解 RecycleView 的 OnItemTouchListener，但如果它没有包含 OnClickListener 这个监听的话，那 Trace 的确就会因为这个原因所以没有生效了。Trace 和 asm-samples 都有双击防抖的功能，但两边的实现思路不一样。Trace 是直接处理 OnClickListener，asm-samples 则是可以去处理各种不同类型的点击事件回调方法。

如果你使用的 RecycleView 的确是通过 OnItemTouchListener 而非 OnClickListener 来处理点击事件的话，那你就要用 asm-samples 了。建议你先把 asm-samples 下载下来，引入你使用的 RecycleView 三方库，然后参照下面的截图，将三方 RecycleView 开放出来的点击事件的回调方法的签名信息写到 hookPointList 里，试试看会不会生效

![](https://github.com/leavesCZY/Trace/assets/30774063/f871993a-ab7a-4d9a-8f17-7cd21976ae6c)

**Comment by HeYongRui** [comment]
好的，我试试，谢谢

**Comment by HeYongRui** [comment]
我试了，不行，你的samples是通过手动在每个地方加注解实现的？我不能每个地方都加吧，而且我用gradle 8.0编译还提示加载DSL失败，感觉还是trace比较适合，trace里是不是在hookpointlist里新增我的第三方adapter的路径就可以实现我的需求了呢，可不可以把这个hookpointlist暴露出来呢，用户就可自定义要拦截的路径，而且trace有办法设置成本地依赖吗

你上面图才是trace里的配置啊，samples没有这个，我也想的是照上图设置，但是那个hookpointlist改了，我无法在本地部署，只能通过你修改暴露hookpointlist接口并且发布新版本才能使用

**Comment by leavesCZY** [comment]
我那个截图就是 sample 里的

**Comment by HeYongRui** [comment]
你是不是samples没上传，我看了没有，你图里的config类是在trace里的，我看了，你应该搞错了两个模块

而且我改了config类里的hookpointlist在本地部署maven，拦截方法没有生效，路径我确认过是对的，我看viewClickclassclassvisitor类里有个viewclassdes和onClickmethoddesc参数，针对我额外添加的hookpointlist路径，是不是这里也要修改才会生效

**Comment by leavesCZY** [comment]
额，好像是你看错了项目，https://github.com/leavesCZY/asm-samples，我截的图就是最新一次提交的

![](https://github.com/leavesCZY/Trace/assets/30774063/6806dad4-c11a-48fe-8225-4678ed6c8ad7)

另外，你只需要修改 hookPointList 即可，但 ViewClickHookPoint 的传值规则对于 类 或者 接口 是不一样的，你要按照实际的回调方法的签名信息来传值噢
