### ISSUE TITLE
compose 怎么不拦截button的onclick呢

### ISSUE THREAD

**Issue by sceneren** [leavesCZY/Track#5]
compose 怎么不拦截button的onclick呢

**Comment by leavesCZY** [comment]
目前没有办法哦，因为 button 方法没有 onClickLabel 参数

**Comment by sceneren** [comment]
好吧，只能自己写个拓展函数用着吧，非常感谢

**Comment by leavesCZY** [comment]
这个其实也有个折中的办法的，你可以不用默认的 button 方法，而是自己来自定义实现一个 button，然后在这个自定义 button 里使用 clickable 方法来设置点击事件
