### ISSUE TITLE
希望加一个代码替换功能

### ISSUE THREAD

**Issue by GuoLiangjun123** [leavesCZY/Track#6]
可以将调用系统安卓id的方法指向到我自定义的方法。

**Comment by leavesCZY** [comment]
有考虑过，但我没想好外部要怎么来声明其想要替换的方法。在我另外一个项目里有这种功能，但需要自己手动引入代码，你可以先去试试： https://github.com/leavesCZY/asm-samples

**Comment by hopper9527** [comment]
> 有考虑过，但我没想好外部要怎么来声明其想要替换的方法。在我另外一个项目里有这种功能，但需要自己手动引入代码，你可以先去试试： https://github.com/leavesCZY/asm-samples

您可以看看滴滴之前的一个插桩库叫droidassist，用xml来配置申明的

**Comment by leavesCZY** [comment]
ok。后续我去研究下

**Comment by leavesCZY** [comment]
你好，你说的这个功能。我能想到的情况有以下几种：

- 替换调用实例方法的指令。类似 telephonyManager.getDeviceId

- 替换调用实例字段的指令。类似 Point().x

- 替换调用静态方法的指令。类似 Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID)

- 替换调用静态字段的指令。类似 Build.BRAND

你看还有什么要补充的吗

**Comment by hopper9527** [comment]
> 你好，你说的这个功能。我能想到的情况有以下几种：
> 
> * 替换调用实例方法的指令。类似 telephonyManager.getDeviceId
> * 替换调用实例字段的指令。类似 Point().x
> * 替换调用静态方法的指令。类似 Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID)
> * 替换调用静态字段的指令。类似 Build.BRAND
> 
> 你看还有什么要补充的吗

目前我们使用场景（合规场景）最多的就是替换调用实例方法的指令和替换调用静态方法的指令，其他的暂时没有补充了

**Comment by leavesCZY** [comment]
ok。目前也大致实现了你说的需求了，代码也已提交。后续我自测没问题了就再发布个正式版本

**Comment by hopper9527** [comment]
> ok。目前也大致实现了你说的需求了，代码也已提交。后续我自测没问题了就再发布个正式版本

好的，辛苦大佬，有需要我抽空跟你一起测试

**Comment by leavesCZY** [comment]
好嘞。Track 里有写了相关的测试代码，对应 replaceFieldTrack 和 replaceMethodTrack。你可以将 Track 发布到本地 mavenLocal 引到自己项目里试试

**Comment by leavesCZY** [comment]
目前 v1.1.0 应该可以满足你的需求了

**Comment by hopper9527** [comment]
> 目前 v1.1.0 应该可以满足你的需求了

麻烦大佬给一个该需求实现的文档链接

**Comment by leavesCZY** [comment]
没有所谓的文档，是有一篇简单的文章介绍：https://juejin.cn/post/7422658245933875252
