### ISSUE TITLE
1.1.0 版本没有发布到远程仓库

### ISSUE THREAD

**Issue by jiyuren** [leavesCZY/Track#7]
你好，1.1.0 版本没有发布到远程仓库，请发布一下

**Comment by leavesCZY** [comment]
有啊。Track 之前的名字是 Trace，你是不是没改。https://plugins.gradle.org/plugin/io.github.leavesczy.track

**Comment by jiyuren** [comment]
不好意思，忘记配置这个了 maven { url "https://plugins.gradle.org/m2/"}

**Comment by leavesCZY** [comment]
soga。大部分都是用的 gradlePluginPortal() 这个源，和你这个应该也一样

**Comment by jiyuren** [comment]
好的，这个是不是无法应用在gradle 7.0上
app 的build.gradle
`plugins {
    id("io.github.leavesczy.track")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.alibaba.arouter'
`
会报这个错
`An exception occurred applying plugin request [id: 'io.github.leavesczy.track']
> Failed to apply plugin 'io.github.leavesczy.track'.
   > Extension of type 'AndroidComponentsExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, ViewClickPluginParameter, ComposeClickPluginParameter, ToastPluginParameter, ReplaceClassPluginParameter, OptimizedThreadPluginParameter, ReplaceInstructionPluginParameter, ReplaceInstructionPluginParameter]
`

**Comment by leavesCZY** [comment]
之前我是有在 7.x 版本上验证过可行的，但 Gradle 小版本太多，我也不好说就全都兼容。你确定你是只将 Track apply 在 app 模块的是吗

**Comment by jiyuren** [comment]
> 之前我是有在 7.x 版本上验证过可行的，但 Gradle 小版本太多，我也不好说就全都兼容。你确定你是只将 Track apply 在 app 模块的是吗

是的，在8.x上的项目是可以的

**Comment by leavesCZY** [comment]
那建议直接升级 Gradle 吧，7.x 也已经挺旧了

**Comment by jiyuren** [comment]
> 那建议直接升级 Gradle 吧，7.x 也已经挺旧了

好的
